// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  RestRestCheckRetrieveResponse,
  SchemaRetrieveData,
  SchemaRetrieveResponse,
  V1TokenLoginCreateData,
  V1TokenLoginCreateResponse,
  V1TokenLogoutCreateResponse,
  V1UsersListData,
  V1UsersListResponse,
  V1UsersCreateData,
  V1UsersCreateResponse,
  V1UsersRetrieveData,
  V1UsersRetrieveResponse,
  V1UsersUpdateData,
  V1UsersUpdateResponse,
  V1UsersPartialUpdateData,
  V1UsersPartialUpdateResponse,
  V1UsersDestroyData,
  V1UsersDestroyResponse,
  V1UsersActivationCreateData,
  V1UsersActivationCreateResponse,
  V1UsersMeRetrieveResponse,
  V1UsersMeUpdateData,
  V1UsersMeUpdateResponse,
  V1UsersMePartialUpdateData,
  V1UsersMePartialUpdateResponse,
  V1UsersMeDestroyResponse,
  V1UsersResendActivationCreateData,
  V1UsersResendActivationCreateResponse,
  V1UsersResetEmailCreateData,
  V1UsersResetEmailCreateResponse,
  V1UsersResetEmailConfirmCreateData,
  V1UsersResetEmailConfirmCreateResponse,
  V1UsersResetPasswordCreateData,
  V1UsersResetPasswordCreateResponse,
  V1UsersResetPasswordConfirmCreateData,
  V1UsersResetPasswordConfirmCreateResponse,
  V1UsersSetEmailCreateData,
  V1UsersSetEmailCreateResponse,
  V1UsersSetPasswordCreateData,
  V1UsersSetPasswordCreateResponse,
} from "./types.gen";

export class RestService {
  /**
   * Check REST API
   * This endpoint checks if the REST API is working.
   * @returns Message
   * @throws ApiError
   */
  public static restRestCheckRetrieve(): CancelablePromise<RestRestCheckRetrieveResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/rest/rest-check/",
    });
  }
}

export class SchemaService {
  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   * @param data The data for the request.
   * @param data.format
   * @param data.lang
   * @returns unknown
   * @throws ApiError
   */
  public static schemaRetrieve(
    data: SchemaRetrieveData = {},
  ): CancelablePromise<SchemaRetrieveResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/schema/",
      query: {
        format: data.format,
        lang: data.lang,
      },
    });
  }
}

export class V1Service {
  /**
   * Use this endpoint to obtain user authentication token.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns TokenCreate
   * @throws ApiError
   */
  public static v1TokenLoginCreate(
    data: V1TokenLoginCreateData = {},
  ): CancelablePromise<V1TokenLoginCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/token/login/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * Use this endpoint to logout user (remove user authentication token).
   * @returns unknown No response body
   * @throws ApiError
   */
  public static v1TokenLogoutCreate(): CancelablePromise<V1TokenLogoutCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/token/logout/",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.limit Number of results to return per page.
   * @param data.offset The initial index from which to return the results.
   * @returns PaginatedUserList
   * @throws ApiError
   */
  public static v1UsersList(
    data: V1UsersListData = {},
  ): CancelablePromise<V1UsersListResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        limit: data.limit,
        offset: data.offset,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserCreate
   * @throws ApiError
   */
  public static v1UsersCreate(
    data: V1UsersCreateData,
  ): CancelablePromise<V1UsersCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.username
   * @returns User
   * @throws ApiError
   */
  public static v1UsersRetrieve(
    data: V1UsersRetrieveData,
  ): CancelablePromise<V1UsersRetrieveResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{username}/",
      path: {
        username: data.username,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.username
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static v1UsersUpdate(
    data: V1UsersUpdateData,
  ): CancelablePromise<V1UsersUpdateResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/users/{username}/",
      path: {
        username: data.username,
      },
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.username
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static v1UsersPartialUpdate(
    data: V1UsersPartialUpdateData,
  ): CancelablePromise<V1UsersPartialUpdateResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{username}/",
      path: {
        username: data.username,
      },
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.username
   * @returns void No response body
   * @throws ApiError
   */
  public static v1UsersDestroy(
    data: V1UsersDestroyData,
  ): CancelablePromise<V1UsersDestroyResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{username}/",
      path: {
        username: data.username,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Activation
   * @throws ApiError
   */
  public static v1UsersActivationCreate(
    data: V1UsersActivationCreateData,
  ): CancelablePromise<V1UsersActivationCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/activation/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns User
   * @throws ApiError
   */
  public static v1UsersMeRetrieve(): CancelablePromise<V1UsersMeRetrieveResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me/",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static v1UsersMeUpdate(
    data: V1UsersMeUpdateData,
  ): CancelablePromise<V1UsersMeUpdateResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/users/me/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static v1UsersMePartialUpdate(
    data: V1UsersMePartialUpdateData = {},
  ): CancelablePromise<V1UsersMePartialUpdateResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns void No response body
   * @throws ApiError
   */
  public static v1UsersMeDestroy(): CancelablePromise<V1UsersMeDestroyResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me/",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns SendEmailReset
   * @throws ApiError
   */
  public static v1UsersResendActivationCreate(
    data: V1UsersResendActivationCreateData,
  ): CancelablePromise<V1UsersResendActivationCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/resend_activation/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns SendEmailReset
   * @throws ApiError
   */
  public static v1UsersResetEmailCreate(
    data: V1UsersResetEmailCreateData,
  ): CancelablePromise<V1UsersResetEmailCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/reset_email/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UsernameResetConfirm
   * @throws ApiError
   */
  public static v1UsersResetEmailConfirmCreate(
    data: V1UsersResetEmailConfirmCreateData = {},
  ): CancelablePromise<V1UsersResetEmailConfirmCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/reset_email_confirm/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns SendEmailReset
   * @throws ApiError
   */
  public static v1UsersResetPasswordCreate(
    data: V1UsersResetPasswordCreateData,
  ): CancelablePromise<V1UsersResetPasswordCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/reset_password/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns PasswordResetConfirm
   * @throws ApiError
   */
  public static v1UsersResetPasswordConfirmCreate(
    data: V1UsersResetPasswordConfirmCreateData,
  ): CancelablePromise<V1UsersResetPasswordConfirmCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/reset_password_confirm/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns SetUsername
   * @throws ApiError
   */
  public static v1UsersSetEmailCreate(
    data: V1UsersSetEmailCreateData,
  ): CancelablePromise<V1UsersSetEmailCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/set_email/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns SetPassword
   * @throws ApiError
   */
  public static v1UsersSetPasswordCreate(
    data: V1UsersSetPasswordCreateData,
  ): CancelablePromise<V1UsersSetPasswordCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/set_password/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }
}
