// This file is auto-generated by @hey-api/openapi-ts

export const $Message = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
  },
  required: ["message"],
} as const;
