// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  RestRestCheckRetrieveResponse,
  SchemaRetrieveData,
  SchemaRetrieveResponse,
} from "./types.gen";

export class RestService {
  /**
   * Check REST API
   * This endpoint checks if the REST API is working.
   * @returns Message
   * @throws ApiError
   */
  public static restRestCheckRetrieve(): CancelablePromise<RestRestCheckRetrieveResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/rest/rest-check/",
    });
  }
}

export class SchemaService {
  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   * @param data The data for the request.
   * @param data.format
   * @param data.lang
   * @returns unknown
   * @throws ApiError
   */
  public static schemaRetrieve(
    data: SchemaRetrieveData = {},
  ): CancelablePromise<SchemaRetrieveResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/schema/",
      query: {
        format: data.format,
        lang: data.lang,
      },
    });
  }
}
